### PR TITLE
Add slha file for GEANT decay of long-lived chargino in AMSB framework

### PR DESCRIPTION
**Pull request by wulsin**
This is to be used in conjunction with this PR:  https://github.com/cms-sw/genproductions/pull/603/

### CODE REVIEW

**Comment by bendavid** [comment]
This is needed for both 76x and 71x

**Comment by ghost** [comment]
@wulsin The cms-data repository is supposed to be used for large files that are not supposed to reside in the CMSSW repository. This 36 lines file can be safely included in cmssw directly.
Thanks.

**Comment by bendavid** [comment]
@degano sorry we need a consistent place/policy for slha files.

The slha files were originally all part of the release, but then they were all moved to cms-data.
I would have been happy to leave them in the cmssw repository, but now that they are here, we'd better update/maintain them here.

Also happy to move them all back to cmssw and maintain them there.

**Comment by wulsin** [comment]
@degano, I was following the recommendation of @bendavid to put this slha file here.  If you and he agree on a better place to put it, I am fine with that.  Just let me know where it should go.  Also this is one slha file for a single mass, lifetime sample.  Once we agree on where it should go, I will make a PR for the rest of the 27 slha files (3 lifetimes x 9 masses).

**Comment by degano** [comment]
@wulsin @bendavid Which CMSSW release should include this? Should we start from 76X?

**Pull request merged**
