### PR TITLE
Fix auxiliary decay files for long lived chargino

### PR DESCRIPTION
**Pull request by scodella**
it was found that an extra line was needed to prevent the chargino to reach the detector even after its decay.

### CODE REVIEW

**Comment by mrodozov** [comment]
assign generators

**Comment by qliphy** [comment]
@scodella   I saw the SLHA doesn't have the extra line "Block" before the "DECAY" line.   See e.g.
http://home.fnal.gov/~skands/slides/slhaecfa.pdf#page=18&zoom=auto,29,-102

Is it specially needed for decay with GEANT4?

If so, do you also need to add lines, such as below?
https://github.com/cms-data/Configuration-Generator/blob/master/AMSB_chargino_100GeV_ctau100cm.slha#L33-L36

**Comment by scodella** [comment]
@qliphy indeed we do not have that line in our usual FastSim scan. It seems to be a special need for GEANT4. The new auxiliary files were successfully tested by the authors, I will ask them to further comment in this thread.

**Comment by mmasciov** [comment]
@qliphy  
As @scodella said, we have privately tested the files as they are in this PR.
The missing "Block" line in the previous files was an issue before. 
The additional lines you point to do not seem necessary.
As already answered, the files are indeed needed so that GEANT4 can properly handle the decays, for FullSim.
Based on our local tests, the changes by @scodella are enough to the purpose of properly simulating the decaying charginos, and its daughters. Hence, from the author side this PR can be accepted as is.

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
This will available in cmssw when  https://github.com/cms-sw/cmsdist/pull/4963 is merged

**Comment by tvami** [comment]
hi @scodella @mmasciov sorry to bother you so many years later, but was there a reason why this was not propagated to 10_6_X ? Is it that you did the study before UL and so you didnt need sample in UL? But then otherwise it would be fine to have these in 10_6_X?

**Comment by mmasciov** [comment]
@tvami, there is no reason I can think of not to propagate this to 10_6_X: propagation would indeed be welcome for the future. The reason was simply that the analysis using the affected samples was done before UL.

**Comment by tvami** [comment]
Thanks @mmasciov !

**Pull request merged**
