### PR TITLE
Slha fix shih chuan high ctau lambda

### PR DESCRIPTION
**Pull request by dnash86**
Upload of checkd and tested SLHA tables for GMSB requests.  Corresponding old files removed here: https://github.com/cms-sw/cmssw/pull/9701

### CODE REVIEW

**Comment by dnash86** [comment]
Set up pull via these commands:

git clone -b 53X_incremental git@github.com:dnash86/Configuration-Generator.git Configuration-Generator
git checkout -b {branch name}
<add/change files>
git add <changed files>
git commit -m "{message}"
git push origin {branch name}

It seems I've removed other files, though?  Should something else be done?

**Comment by bendavid** [comment]
Sorry this pull request is for the wrong branch.
Should be made against https://github.com/cms-data/Configuration-Generator/tree/53X_incremental instead.

**Comment by dnash86** [comment]
Ah, right.  Creating that pull now.

**Comment by bendavid** [comment]
please close this one.

**Pull request closed without merging**
