### PR TITLE
New decay tables for two SUSY models

### PR DESCRIPTION
**Pull request by scodella**
New decay tables for two SUSY models:
1) long lived  Stau
2) General Gauge Mediation model

### CODE REVIEW

**Comment by smuzaffar** [comment]
@alberto-sanchez, @qliphy  any objections?
@scodella , these are new files, is there any cmssw PR to make use of these?

**Comment by scodella** [comment]
@smuzaffar these files are to be use for susy signal production under different campaigns: RunIISummer15GS, RunIIFall17GS, RunIIFall18GS, RunIISummer16FSPremix, RunIIFall17FSPremix, RunIIAutumn18FSPremix

**Comment by scodella** [comment]
Is there any issue on this or can we move forward?

**Comment by agrohsje** [comment]
sorry missed this PR. no objections.
+1

**Comment by agrohsje** [comment]
+1

**Comment by mrodozov** [comment]
+externals

**Comment by scodella** [comment]
Thanks. We would like to have these files backported to the releases in [1] for SUSY signal production. Could you please remind me the procedure? Who would be the "corresponding L2"?

[1] 
RunIISummer15GS -> CMSSW_7_1_X
RunIIFall17GS -> CMSSW_9_3_X
RunIIFall18GS -> CMSSW_10_2_X
RunIISummer16FSPremix -> CMSSW_8_0_X
RunIIFall17FSPremix -> CMSSW_9_4_X
RunIIAutumn18FSPremix -> CMSSW_10_2_X

**Comment by mrodozov** [comment]
Once this is merged I'll backport it.

**Comment by silviodonato** [comment]
@scodella do you really need to backport this in all those six releases? Could you comment on this? If you are interest to produce new signals using UL you can use 10_6_X for all three years.

**Comment by silviodonato** [comment]
@scodella @mrodozov

**Comment by mrodozov** [comment]
@silviodonato we can merge this for CMSSW_11_1_X and decide later on backports

**Comment by silviodonato** [comment]
+1
@mrodozov ok

**Comment by scodella** [comment]
> @scodella do you really need to backport this in all those six releases? Could you comment on this? If you are interest to produce new signals using UL you can use 10_6_X for all three years.

@silviodonato We need the slha files in [1] in the three fastsim releases to prouce signals for analyses aiming to summer conferences. As for [2], they are in principle needed to produce LL stau signals required in fallsim, but we are waiting authors to confirm.


[1]
https://github.com/scodella/Configuration-Generator/tree/master/SUSY/GGM_Full
[2] https://github.com/scodella/Configuration-Generator/tree/master/SUSY/LongLivedStau

**Comment by smuzaffar** [comment]
@mrodozov , I have merged this for CMSSW_11_1_X, please go ahead with back ports PRs for these releases  https://github.com/cms-data/Configuration-Generator/pull/9#issuecomment-578647858

**Comment by smuzaffar** [comment]
@scodella , do we really need these to be back ported to all releases you mentioned here https://github.com/cms-data/Configuration-Generator/pull/9#issuecomment-578647858

**Comment by scodella** [comment]
@smuzaffar We actually just got an update from the authors of LL stau analysis. It seems that we will need to produce only FastSim signal for the GGM model, so the following release will be enough:

RunIISummer16FSPremix -> CMSSW_8_0_X
RunIIFall17FSPremix -> CMSSW_9_4_X
RunIIAutumn18FSPremix -> CMSSW_10_2_X

**Comment by silviodonato** [comment]
@mrodozov could you prepare the three PRs (CMSSW_8_0_X, CMSSW_9_4_X, CMSSW_10_2_X) to cmsdist, please?
cc: @smuzaffar  @makortel

**Comment by mrodozov** [comment]
they are already merged :) meaning in the latest IBs as well

**Comment by silviodonato** [comment]
Uh, right! Great, thanks! :-)

https://github.com/cms-sw/cmsdist/pull/5433 master
https://github.com/cms-sw/cmsdist/pull/5582 CMSSW_7_1_X
https://github.com/cms-sw/cmsdist/pull/5581 CMSSW_8_0_X
https://github.com/cms-sw/cmsdist/pull/5579 CMSSW_9_4_X
https://github.com/cms-sw/cmsdist/pull/5578 CMSSW_10_2_X

**Comment by scodella** [comment]
Hi,

I'd like to inquire on the status of the cutting for the various releases. I have found the announcement for 10_2_X but not for the others. Is there any timeline for them? Sorry if I missed any announcement.

**Comment by smuzaffar** [comment]
@scodella , this has been integrated in CMSSW_8_0_X, CMSSW_9_4_X, CMSSW_10_2_X IBs. It was part of CMSSW_10_2_21 release. We have not build any release for 8.0.X and 9.4.X. When ever we decided to build a full release for these release cycles then this data should be there. @silviodonato , can tell more when he wants to build full releases for these release cycles.

**Comment by silviodonato** [comment]
Hi @scodella , 
the releases are made when they are needed by somebody. We can update the releases by next week. Do you have any preference about the order?

**Comment by silviodonato** [comment]
I mean: which release do you prefer to have first?

**Comment by scodella** [comment]
Hi @silviodonato 

having already CMSSW_10_2_21, our preferences are:

cms-sw/cmsdist#5579 CMSSW_9_4_X first
cms-sw/cmsdist#5581 CMSSW_8_0_X later

**Comment by silviodonato** [comment]
@scodella  I'm sure you saw the release announcements . 
Just to be 100% sure, the releases are ready:
https://github.com/cms-sw/cmssw/releases/CMSSW_9_4_17
https://github.com/cms-sw/cmssw/releases/CMSSW_8_0_35

**Comment by scodella** [comment]
@silviodonato thanks!

**Comment by agrohsje** [comment]
Already included for production. Thanks so much!

**Pull request merged**
