### PR TITLE
Fix charge typo for Q=1 tau-prime

### PR DESCRIPTION
**Pull request by tvami**
Found a typo in https://github.com/cms-data/Configuration-Generator/pull/10/
Charges are measured in quark charges, so for Q=1e it should have been 3

### CODE REVIEW

**Comment by tvami** [comment]
@perrotta sorry I found a typo in the prev PR, this should fix that.

**Comment by perrotta** [comment]
+orp
- Quite reasonable fix

**Comment by Saptaparna** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by tvami** [comment]
@cmsbuild , please test
 * it doesnt do anything but it seems we need to do it for the merge?

**Comment by smuzaffar** [comment]
orp has signed it, so lete merge it and include it for next 13.1.X IB

**Pull request merged**
