### PR TITLE
decay tables for a compresed gluino model

### PR DESCRIPTION
**Pull request by scodella**
New decay tables for a compresed gluino model

### CODE REVIEW

**Comment by efeyazgan** [comment]
+1

**Comment by scodella** [comment]
any issue holding the merging of this PR? thanks

**Comment by efeyazgan** [comment]
@smuzaffar

**Comment by smuzaffar** [comment]
@scodella , these are all new files. Is there any cmssw PR which make use of these new files?

**Comment by scodella** [comment]
@smuzaffar , we intend to use them in the production of new susy signal datasets in the RunIISummer15GS campaign. So this should be backported to 71X.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
