### PR TITLE
Slha fix shih chuan high ctau lambda

### PR DESCRIPTION
**Pull request by dnash86**
Apparently it cannot merge - is there a merge conflict?

### CODE REVIEW

**Comment by dnash86** [comment]
Definitely a merge conflict, how can I fix?  I tried:

git pull upstream 53X_incremental:SLHA-Fix-ShihChuan-high-ctau-lambda

from the folder I issued the push from, but but apparently 'upstream' isn't a git repository.

**Comment by bendavid** [comment]
try from a clean are?

**Comment by bendavid** [comment]
area

**Comment by dnash86** [comment]
Should I start the clean area as such: 

git clone -b 53X_incremental git@github.com:dnash86/Configuration-Generator.git Configuration-Generator

(Taken from an old email from you.)  Or perhaps not?

**Comment by bendavid** [comment]
No, start from a clean area of the upstream repository ie
git clone -b 53X_incremental https://github.com/cms-data/Configuration-Generator.git

**Comment by dnash86** [comment]
That seems to have worked, but had fewer files changed than expected, let me double check things quickly, before merging.

**Comment by dnash86** [comment]
Okay, all files are now present.  Ready for merging.

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
@degano - could you take care of this request in 53x. Thanks

**Comment by ghost** [comment]
Done here:
https://github.com/cms-sw/cmsdist/pull/1637
Cheers,
Alessandro

**Comment by davidlange6** [comment]
Thanks!

**Pull request merged**
