### PR TITLE
Long-lived stop with 2-body and 4-body decays (Supplementary)

### PR DESCRIPTION
**Pull request by Ang-Li-95**
Added necessary files for stop masses of 1100 and 1300GeV:
- `hscppythiapdtstop1100.tbl`
- `hscppythiapdtstop1300.tbl`
- `particles_stop_1100_GeV.txt`
- `particles_stop_1300_GeV.txt`

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
ignore tests-rejected with ib-failure

**Comment by tvami** [comment]
@smuzaffar please approve this

**Comment by smuzaffar** [comment]
+externals

Only new files

**Comment by bbilin** [comment]
+1

**Comment by tvami** [comment]
@antoniovilela, @mandrenguyen please merge this!

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
