### PR TITLE
Adding slha files for EXO DisappTrk Run 3 analysis

### PR DESCRIPTION
**Pull request by borzari**
Distinct mass/ctau slha files for the central production of LL charginos signal samples for the EXO disappearing tracks analysis in Run 3.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by menglu21** [comment]
+1

**Comment by tvami** [comment]
hi @smuzaffar can you please merge this?

**Comment by smuzaffar** [comment]
This PR only adds new files, so testing without cmssw PR (which actually make sure of these files) is only going to check if packaging works. Is there any cmssw PR to go with it?

**Comment by tvami** [comment]
>  Is there any cmssw PR to go with it?

hi @smuzaffar this is used in McM for signal generation, so there is no main cmssw PR to go with.

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
so by default itwill go to 13.3.X release cycle. let us know if this should be backported to any older release cycle

**Comment by tvami** [comment]
> let us know if this should be backported to any older release cycle

yes, it needs to go back to 12_4_X for the 2022 MC productions. I remember that there used to be a tag update in cmsdist to do this, but I dont see the master PR for that automatically triggered.

**Comment by tvami** [comment]
> but I dont see the master PR for that automatically triggered.

nvm, it did come up 4 min after I wrote this :)

**Comment by smuzaffar** [comment]
we are updating bot scripts to python3 and automatic master branch PR creation [script](https://github.com/cms-sw/cms-bot/blob/master/create-new-data-pr.py) had a bug. https://github.com/cms-sw/cms-bot/commit/a4f7e3eeb0f338039a0884ba419b74b125609736 has fixed the issue :-)

**Pull request merged**
