### PR TITLE
Long-lived stop with 2-body and 4-body decays

### PR DESCRIPTION
**Pull request by Ang-Li-95**
SLHA files for long-lived stop with 2-body and 4-body decays. The branching ratio is 50% for each decay channels.
2-body: stop -> c + neutrlino
4-body: stop -> b + W + neutralino, W decays to a pair of fermions

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
assign analysis

**Comment by tvami** [comment]
+analysis
 * the error is unrelated

@smuzaffar there is not corresponding cmssw-sw PR for this, we need these files for UL signal production (so we'll have to backport the tag when this is merged)

**Comment by smuzaffar** [comment]
+externals

only new files.

**Comment by lviliani** [comment]
+1

**Comment by tvami** [comment]
@mandrenguyen, @antoniovilela, please merge this so we can take care of the backports (which is the real important one), thanks!

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
