### PR TITLE
Required files for long lived multiply charged particles UL MC campaign

### PR DESCRIPTION
**Pull request by RafeyH**
Adding required files for long lived multiply charged massive particles (mchamps) UL MC campaign - pythia8 version

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by menglu21** [comment]
+1

**Comment by tvami** [comment]
@smuzaffar @rappoccio @antoniovilela  can you please sign and merge? We need the backport of this in 10_6_X so we need this in asap

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@rappoccio @antoniovilela  feel free to merge it and include 14.0.X. Once it is merged for 14.0.X then I will open a 10.6.X backport

**Comment by tvami** [comment]
@rappoccio can you please merge this?

**Comment by rappoccio** [comment]
+1

**Pull request merged**
