### PR TITLE
Add tau-prime samples with mass 1200,1600,2000 GeV

### PR DESCRIPTION
**Pull request by tvami**
These mass points were missing earlier. Needed for EXO LL HSCP search

### CODE REVIEW

**Comment by tvami** [comment]
@perrotta @smuzaffar technically I need this in the 10_6_X release, I'm not sure if any tags need to be updated for this to propagate back there

**Comment by Saptaparna** [comment]
+1
in advance

**Comment by tvami** [comment]
@cmsbuild , please test
 * although nothing directly tests this in CMSSW, it's just needed for McM

**Comment by perrotta** [comment]
@tvami this only adds new files, and as such I don't see possible issues in merging it.
Just to get some context: which code is using these data files? Is there an open PR that requires them? Otherwise, why there is no workflow crashing while they were missing? Or, if they are only used by some private code, why not to keep private also them?

**Comment by tvami** [comment]
Hi Andrea, it's needed for central signal production in McM. No change in the main CMSSSW is needed, but it's also not private since it goes through the central McM machinery. Thanks for merging it quickly!

**Comment by tvami** [comment]
> for central signal production in McM

which is using CMSSW_10_6_30, so my question was: we merge the cms-data here, will the CMSSW_10_6_30 see the new files?

**Comment by perrotta** [comment]
> +1 in advance

@Saptaparna I take this as a +1 from generators, even if when written in a single line is not recognized by bot as a signature

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
> > for central signal production in McM
> 
> which is using CMSSW_10_6_30, so my question was: we merge the cms-data here, will the CMSSW_10_6_30 see the new files?

We need a cmsdist pull request for all cycles in which these data files are required.
Besides master and 10_6_X, in which other release cycles you want these in?
By the way, you ask specifically 10_6_30, but the most recent release in 10_6_X is 10_6_32_patch1, and we'll need to build a 10_6_33 if we want to include also these data. I assume this is still fine with you

**Comment by tvami** [comment]
> Besides master and 10_6_X, in which other release cycles you want these in?

I dont think we need anything else.

>  you ask specifically 10_6_30,

Sorry, I really meant to say 10_6_30 or higher. Cutting CMSSW_10_6_33 sounds good for me! Thanks again!

**Comment by perrotta** [comment]
merge

**Comment by perrotta** [comment]
The Configuration-Generator tag for 10_6_X is V01-00-03, while the tag that includes this update is V01-03-00
Is it correct to jump directly from V01-00-03 to the new V01-03-00 in 10_6_X? Where all intermediate tags only including additional files (in which case there are no issue in adding them) or where there some more convoluted changes instead?
It is true that we can always test that new tag in 10_6 and see what happens, but it would be great if @Saptaparna or someone else from generators could confirm.

**Pull request merged**
